/*
 * @license NewConsensus Platform v0.1
 * (c) 2020-2021 KaoGeek. http://kaogeek.dev
 * License: MIT. https://opensource.org/licenses/MIT
 * Author: chalucks <chaluck.s@absolute.co.th>, shiorin <junsuda.s@absolute.co.th>
 */
 
export enum PROPOSAL_LOG_ACTION {
    CREATE = 'CREATE',
    EDIT = 'EDIT',
    DELETE = 'DELETE',
    APPROVE = 'APPROVE',
    UNAPPROVE = 'UNAPPROVE',
    SUPPORTER = 'SUPPORTER',
    LIKE = 'LIKE',
    DISLIKE = 'DISLIKE',
    REMOVE_LIKE = 'REMOVE_LIKE',
    REMOVE_DISLIKE = 'REMOVE_DISLIKE'
}

export enum PROPOSAL_COMMENT_LOG_ACTION {
    CREATE = 'COMMENT_CREATE',
    EDIT = 'COMMENT_EDIT',
    DELETE = 'COMMENT_DELETE',
    LIKE = 'COMMENT_LIKE',
    DISLIKE = 'COMMENT_DISLIKE',
    REMOVE_LIKE = 'REMOVE_COMMENT_LIKE',
    REMOVE_DISLIKE = 'REMOVE_COMMENT_DISLIKE',
    APPROVE = 'COMMENT_APPROVE',
    UNAPPROVE = 'COMMENT_UNAPPROVE',
}

export enum DEBATE_LOG_ACTION {
    CREATE = 'CREATE',
    EDIT = 'EDIT',
    DELETE = 'DELETE',
    LIKE = 'LIKE',
    DISLIKE = 'DISLIKE',
    REMOVE_LIKE = 'REMOVE_LIKE',
    REMOVE_DISLIKE = 'REMOVE_DISLIKE'
}

export enum DEBATE_COMMENT_LOG_ACTION {
    CREATE = 'COMMENT_CREATE',
    EDIT = 'COMMENT_EDIT',
    DELETE = 'COMMENT_DELETE',
    LIKE = 'COMMENT_LIKE',
    DISLIKE = 'COMMENT_DISLIKE',
    REMOVE_LIKE = 'REMOVE_COMMENT_LIKE',
    REMOVE_DISLIKE = 'REMOVE_COMMENT_DISLIKE',
    APPROVE = 'COMMENT_APPROVE',
    UNAPPROVE = 'COMMENT_UNAPPROVE',
}

export enum VOTE_LOG_ACTION {
    CREATE = 'CREATE',
    EDIT = 'EDIT',
    DELETE = 'DELETE',
    LIKE = 'LIKE',
    DISLIKE = 'DISLIKE',
    REMOVE_LIKE = 'REMOVE_LIKE',
    REMOVE_DISLIKE = 'REMOVE_DISLIKE'
}

export enum VOTE_COMMENT_LOG_ACTION {
    CREATE = 'COMMENT_CREATE',
    EDIT = 'COMMENT_EDIT',
    DELETE = 'COMMENT_DELETE',
    LIKE = 'COMMENT_LIKE',
    DISLIKE = 'COMMENT_DISLIKE',
    REMOVE_LIKE = 'REMOVE_COMMENT_LIKE',
    REMOVE_DISLIKE = 'REMOVE_COMMENT_DISLIKE',
    APPROVE = 'COMMENT_APPROVE',
    UNAPPROVE = 'COMMENT_UNAPPROVE',
}

export enum MAINPAGE_SLIDE_LOG_ACTION {
    CREATE = 'CREATE_MAINPAGE_SLIDE',
    EDIT = 'EDIT_MAINPAGE_SLIDE',
    DELETE = 'DELETE_MAINPAGE_SLIDE'
}

export enum MAINPAGE_VIDEO_LOG_ACTION {
    CREATE = 'CREATE_MAINPAGE_VIDEO',
    EDIT = 'EDIT_MAINPAGE_VIDEO',
    DELETE = 'DELETE_MAINPAGE_VIDEO'
}

export enum USER_EXP_STATEMENT {
    CREATE = 'CREATE',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
    CREATE_COMMENT_VOTE = 'CREATE_COMMENT_VOTE',
    COMMENT = 'COMMENT',
    LIKE = 'LIKE',
    DISLIKE = 'DISLIKE',
    UNLIKE = 'UNLIKE',
    UNDISLIKE = 'UNDISLIKE',
    HOT = 'HOT',
    RECOMMEND = 'RECOMMEND',
    SUPPORT = 'SUPPORT',
    UNSUPPORT = 'UNSUPPORT',
    HALF_SUPPORT = 'HALF_SUPPORT',
    FULL_SUPPORT = 'FULL_SUPPORT'
} 

export enum CONTENT_TYPE {
    DEBATE = 'DEBATE',
    PROPOSAL = 'PROPOSAL',
    VOTE = 'VOTE'
}
